parameters:
#    libertribes_jeu.example.class: Libertribes\JeuBundle\Example

services:
#    libertribes_jeu.example:
#        class: %libertribes_jeu.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
