LibertribesGameBundle:
    resource: "@LibertribesGameBundle/Resources/config/routing.yml"
    prefix:   /

LibertribesWorldsCreationBundle:
    resource: "@LibertribesWorldsCreationBundle/Resources/config/routing.yml"
    prefix:   /worldsCreation

LibertribesCommerceBundle:
    resource: "@LibertribesCommerceBundle/Resources/config/routing.yml"
    prefix:   /commerce

LibertribesWorldBundle:
    resource: "@LibertribesWorldBundle/Resources/config/routing.yml"
    prefix:   /

LibertribesForumBundle:
    resource: "@LibertribesForumBundle/Resources/config/routing.yml"
    prefix:   /forum

login:
    pattern:  /login
    defaults: { _controller: "LibertribesSecurityBundle:Security:login" }

login_check:
    pattern:  /login_check
    defaults: { _controller: "LibertribesSecurityBundle:Security:login" }

register:
    pattern:  /register
    defaults: { _controller: "LibertribesSecurityBundle:Registration:register" }