libertribes_world:
  width: 100
  height: 100
  image: "%kernel.root_dir%/config/world.png"
  cartographer:
    directory: %world_cartographer_directory%
  sections:
    directory: %world_sections_directory%
    width: 256
    height: 256
  lands:
    - { color: '000000', name: black land }
    - { color: 'ffffff', name: white land }
  panels:
    - name: '16x16'
      tiles :
        directory: "%kernel.root_dir%/tiles/16"
        width : 16
        height : 16
    - name: '32x32'
      tiles :
        directory: "%kernel.root_dir%/tiles/32"
        width : 32
        height : 32
    - name: '64x64'
      tiles :
        directory: "%kernel.root_dir%/tiles/64"
        width : 64
        height : 64
    - name: 'test'
      tiles :
        directory: "%kernel.root_dir%/tiles/test"
        width : 64
        height : 52         
