LibertribesWorldBundle_StaticMap_index:
    pattern:  /map/{panel_name}/{box}
    defaults:
      _controller: LibertribesWorldBundle:StaticMap:index
      panel_name: 16x16
      box: e8,e8,0,0

LibertribesWorldBundle_InteractiveMap_index:
    pattern:  /interactive-map/{panel_name}
    defaults:
      _controller: LibertribesWorldBundle:InteractiveMap:index
      panel_name: 16x16
