parameters:
    libertribes_world.world.class: Libertribes\Component\World\World
    libertribes_world.cartographers.class: Libertribes\Bundle\WorldBundle\Service\CartographerManager
    libertribes_world.panels.class: Libertribes\Bundle\WorldBundle\Service\TilePanelManager

services:
    libertribes_world.world:
        class: "%libertribes_world.world.class%"
        arguments: [%libertribes_world.world.width%, %libertribes_world.world.height%]
        calls:
          - [ setImage, [ %libertribes_world.world.image% ] ]
          - [ setLandTypes, [ %libertribes_world.lands% ] ]
    libertribes_world.panels:
        class: "%libertribes_world.panels.class%"
        arguments: [%libertribes_world.sections.directory%, %libertribes_world.sections.width%, %libertribes_world.sections.height%, %libertribes_world.panels%]
    libertribes_world.cartographers:
        class: "%libertribes_world.cartographers.class%"
        arguments: [%libertribes_world.cartographer.directory%, @libertribes_world.world, @libertribes_world.panels]
