forum_welcome:
    pattern:  /
    defaults: { _controller: LibertribesForumBundle:Forum:index }
forum_category_list:
    pattern:  /category
    defaults: { _controller: LibertribesForumBundle:Category:index }
forum_post_list:
    pattern:  /post/{topicid}
    defaults: { _controller: LibertribesForumBundle:Post:index, topicid : 1 }
    requirements:
        topicid:  \d+
forum_topic_list:
    pattern:  /topic/{categoryid}-{categoryname}
    defaults: { _controller: LibertribesForumBundle:Topic:index, categoryid : 1, categoryname : "" }
    requirements:
        categoryid:  \d+
forum_topic_findbyid:
    pattern:  /topic/byId/{topicid}
    defaults: { _controller: LibertribesForumBundle:Topic:findById, topicid : 1}
    requirements:
        topicid:  \d+

forum_new_post:
    pattern:  /post/newpost/
    defaults: { _controller: LibertribesForumBundle:Post:newpost }
    requirements:
        _method:  POST
forum_new_topic:
    pattern:  /topic/new/
    defaults: { _controller: LibertribesForumBundle:Topic:createnewtopic }
    requirements:
        _method:  POST
forum_search:
    pattern:  /search
    defaults: { _controller: LibertribesForumBundle:Forum:search }
    requirements:
        _method:  POST

