parameters:
#    libertribes_commerce.example.class: Libertribes\CommerceBundle\Example

services:
#    libertribes_commerce.example:
#        class: %libertribes_commerce.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
